function(snake_to_pascal in_string out_string)
    string(REPLACE "_" ";" temp_list "${in_string}")
    set(pascal_string "")
    foreach(part IN LISTS temp_list)
        string(SUBSTRING "${part}" 0 1 first_char)
        string(TOUPPER "${first_char}" capitalized_first_char)
        string(SUBSTRING "${part}" 1 -1 rest_part)
        set(pascal_string "${pascal_string}${capitalized_first_char}${rest_part}")
    endforeach()
    set(${out_string} "${pascal_string}" PARENT_SCOPE)
endfunction()